import axios from "axios";
import {
  getModel,
  invokeWithFallback,
  getGroq,
  getGemini,
} from "../config/model.js";
import { uploadImageToCloudinary } from "../config/cloudinary.js";

const cleanEnv = (val) =>
  val
    ? String(val)
        .trim()
        .replace(/^["']|["']$/g, "")
    : "";

const enhancePrompt = async (rawPrompt) => {
  try {
    let primaryLlm;
    let fallbackLlm;
    try {
      primaryLlm = getGroq();
    } catch {
      primaryLlm = getModel("chat");
    }
    try {
      fallbackLlm = getGemini();
    } catch {
      fallbackLlm = null;
    }

    const systemPrompt = `You are an expert AI prompt engineer specializing in Clipdrop AI (SDXL).
Transform the user's prompt into an ultra-detailed, evocative, and photorealistic visual description.
Focus on: subject details, atmosphere, lighting (e.g. golden hour, volumetric rays, neon backlight), camera angle, artistic style, and textures.
Keep it under 50 words.
Do NOT include preamble, markdown fences, or quotes. Output ONLY the refined prompt text.

User Request: "${rawPrompt}"`;

    const res = await invokeWithFallback(primaryLlm, fallbackLlm, systemPrompt);
    const refined = (
      typeof res?.content === "string" ? res.content : ""
    ).trim();
    return refined && refined.length > 5 ? refined : rawPrompt;
  } catch (err) {
    console.warn(
      "[Image Agent] Prompt enhancement skipped, using raw prompt:",
      err.message,
    );
    return rawPrompt;
  }
};
const generateWithClipdrop = async (prompt, apiKey) => {
  if (!apiKey) {
    throw new Error(
      "CLIPDROP_API_KEY is missing. Please set CLIPDROP_API_KEY in server/services/agent/.env",
    );
  }

  console.log(
    "[Clipdrop AI] Generating image via Clipdrop Text-to-Image API...",
  );

  const form = new FormData();
  form.append("prompt", prompt);

  const response = await axios.post(
    "https://clipdrop-api.co/text-to-image/v1",
    form,
    {
      headers: {
        "x-api-key": apiKey,
      },
      responseType: "arraybuffer",
      timeout: 60000,
    },
  );

  if (response.status === 200 && response.data) {
    console.log("[Clipdrop AI] Image successfully generated by Clipdrop!");
    return Buffer.from(response.data);
  }

  throw new Error(`Clipdrop API responded with status ${response.status}`);
};

/**
 * Image Generation Agent
 * Exclusively uses Clipdrop AI and uploads generated images to Cloudinary
 */
export const imageGenAgent = async (state) => {
  console.log("--> Selected Agent: image (Clipdrop AI Exclusive)");
  const userPrompt = (state?.prompt || "").trim();
  console.log("Image agent received prompt:", userPrompt);

  if (!userPrompt) {
    return {
      ...state,
      aiResponse:
        "Please describe the image you want me to generate with Clipdrop AI.",
      images: [],
    };
  }

  const seed = Math.floor(Math.random() * 1000000);
  const clipdropApiKey = cleanEnv(process.env.CLIPDROP_API_KEY);

  if (!clipdropApiKey) {
    return {
      ...state,
      aiResponse:
        "⚠️ **Clipdrop API Key is missing!**\n\nPlease add your `CLIPDROP_API_KEY` in `server/services/agent/.env` to generate images with Clipdrop AI.",
      images: [],
    };
  }

  try {
    const enhancedPrompt = await enhancePrompt(userPrompt);
    console.log("[Clipdrop AI] Refined prompt:", enhancedPrompt);

    const imageBuffer = await generateWithClipdrop(
      enhancedPrompt,
      clipdropApiKey,
    );

    console.log("[Clipdrop AI] Uploading generated image to Cloudinary...");
    const cloudinaryResult = await uploadImageToCloudinary(imageBuffer, {
      folder: "ai_generated_images",
      public_id: `clipdrop_${Date.now()}_${seed}`,
      tags: ["clipdrop", "ai_image", "multiagent_bot"],
    });

    const finalImageUrl = cloudinaryResult.url;
    const isStored = cloudinaryResult.storedInCloudinary;

    console.log("[Clipdrop AI] Final Cloudinary URL:", finalImageUrl);

    const markdownResponse = `### 🎨 Clipdrop AI Generated Image

![${userPrompt.replace(/"/g, "'")}](${finalImageUrl})

---
- **Prompt**: *${userPrompt}*
- **Enhanced Style**: *${enhancedPrompt}*
- **AI Model**: Clipdrop AI (Text-to-Image / SDXL)
- **Storage**: ${isStored ? "☁️ **Permanently stored on Cloudinary**" : "🌐 Direct Cloudinary Upload"}

🔗 [Open Full Image](${finalImageUrl})`;

    return {
      ...state,
      aiResponse: markdownResponse,
      images: [finalImageUrl],
    };
  } catch (error) {
    console.error("[Clipdrop AI] Error generating image:", error.message);

    let errorDetail = error.message;
    if (error.response?.data) {
      try {
        const errorText = Buffer.isBuffer(error.response.data)
          ? error.response.data.toString("utf-8")
          : JSON.stringify(error.response.data);
        errorDetail = errorText;
      } catch {}
    }

    return {
      ...state,
      aiResponse: `❌ **Clipdrop AI Error**: Failed to generate image.\n\n*Details*: \`${errorDetail}\`\n\nPlease check your Clipdrop API key balance and try again.`,
      images: [],
    };
  }
};
